= AStorage-Java

image:https://img.shields.io/badge/vert.x-4.4.4-white.svg[link="https://vertx.io"]

.Already supported formats (See usage examples below):
* Fasta
* dbNSFP v4.3a
* gnomAD v2.1.1
* SpliceAI v1.3
* PharmGKB
* ClinVar

== Building

To launch the tests:
[source]
----
./mvnw clean test
----

To package the application:
[source]
----
./mvnw clean package
----

To start the application:
[source]
----
./mvnw clean compile exec:java
----

== Usage examples

The service is only running on *localhost:8080* for now. It creates DB directories in the user's home directory if not specified otherwise.

DB directory can be adjusted using a *config.json* file:
[source]
----
{
	"dataDirectoryPath": "/home/user/ExampleStorage"
}
----
To start the application:
[source]
----
java -jar astorage-java-1.0.0.jar [config_json_path]
----

.*Fasta*
[%collapsible]
====
To ingest data:
[source]
----
curl -X POST "localhost:8080/query/fasta?arrayName=<arr_name>&dataURL=<data_url>&metadataURL=<metadata_url>"
----

To query data:
[source]
----
curl "localhost:8080/query/fasta?arrayName=<arr_name>&sectionName=<sec_name>&startPosition=<start_pos>&stopPosition=<stop_pos>"
----
====

.*dbNSFP v4.3a*
[%collapsible]
====
To ingest data:
[source]
----
curl -X POST "localhost:8080/ingestion/dbnsfp?dataPath=<data_path>"
----

To query data:
[source]
----
curl "localhost:8080/query/dbnsfp?chr=<chr_num>&pos=<pos>&alt=<alt_nucleotide>"
----
====

.*gnomAD v2.1.1*
[%collapsible]
====
To ingest data:
[source]
----
curl -X POST "localhost:8080/ingestion/gnomad?dataUrl=<data_url>&sourceType=<src_type>"
----

To query data:
[source]
----
curl "localhost:8080/query/gnomad?chr=<chr_num>&pos=<pos>&sourceType=<src_type>"
----
====

.*SpliceAI v1.3*
[%collapsible]
====
To ingest data:
[source]
----
curl -X POST "localhost:8080/ingestion/spliceai?dataPath=<data_path>"
----

To query data:
[source]
----
curl "localhost:8080/query/spliceai?chr=<chr_num>&pos=<pos>"
----
====

.*PharmGKB*
[%collapsible]
====
To ingest data:
[source]
----
curl -X POST "localhost:8080/ingestion/pharmgkb?dataType=<data_type>&dataPath=<data_path>"
----

To query data:
[source]
----
curl "localhost:8080/query/pharmgkb?dataType=<data_type>&id=<id>"
----
====

.*ClinVar*
[%collapsible]
====
To ingest data:
[source]
----
curl -X POST "localhost:8080/ingestion/clinvar?dataPath=<data_path>&dataSummaryPath=<data_summary_path>"
----

To query data:
[source]
----
curl "localhost:8080/query/clinvar?chr=<chr_num>&startPos=<start_pos>&endPos=<end_pos>"
----
====

To batch-query data:
[source]
----
curl -X POST \
	-H "Content-Type: application/json" \
	-d @query_file.json \
	"localhost:8080/batch-query/<format_name>" > results.jsonl
----

*query_file.json* example for *dbNSFP* (Batch query parameters match single query parameters for every format):
[source]
----
[
	{"chr": 21, "pos": 5011799, "alt": "A"},
	{"chr": 21, "pos": 5011800},
	{"chr": 16, "pos": 62584, "alt": "T"}
]
----

To stop the service:
[source]
----
curl "localhost:8080/stop"
----
